name: Flutter Lint

on:
  push:
    branches:
      - main
    paths:
      - cping/**
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - cping/**
      - .github/workflows/**

defaults:
  run:
    working-directory: ./cping

jobs:
  flutter-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "22.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
      - name: Get dependencies
        run: flutter pub get
      - name: Check formatting
        run: dart format -o show --set-exit-if-changed .
      - name: Run Flutter analysis
        run: flutter analyze
