name: API Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    working-directory: ./api

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t cping_flask_api:test --target test .
      - name: Run tests
        run: |
          docker run --rm cping_flask_api:test
