name: Run API

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *"

jobs:
  run-api:
    runs-on: ubuntu-latest
    # services:
    #   api:
    #     image: ${{vars.DOCKERHUB_USERNAME}}/${{vars.API_DOCKER_IMAGE_NAME}}
    #     env:
    #       API_KEY: ${{secrets.API_KEY}}
    #       GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.FIREBASE_CREDENTIALS}}
    #       GOOGLE_CLOUD_PROJECT: ${{vars.GCLOUD_PROJECT}}
    #     ports:
    #       - 80:80
    steps:
      - name: Start API container
        run: |
          docker run --rm -d \
            -p 80:80 \
            --env API_KEY=${{secrets.API_KEY}} \
            --env GOOGLE_APPLICATION_CREDENTIALS=${{secrets.FIREBASE_CREDENTIALS}}
            --env GOOGLE_CLOUD_PROJECT=${{vars.GCLOUD_PROJECT}}
            ${{vars.DOCKERHUB_USERNAME}}/${{vars.API_DOCKER_IMAGE_NAME}}
      - name: Ping check
        run: |
          curl --location 'localhost/' \
            --header 'Authorization: Bearer ${{secrets.API_KEY}}'
      - name: Update contest cache for Codeforces
        run: |
          curl --location 'localhost/api/contests/?website=codeforces&cache' \
            --header 'Authorization: Bearer ${{secrets.API_KEY}}'
      - name: Update contest cache for AtCoder
        run: |
          curl --location 'localhost/api/contests/?website=atcoder&cache' \
            --header 'Authorization: Bearer ${{secrets.API_KEY}}'
